### ISSUE TITLE
Add support for voice-call

### ISSUE THREAD

**Issue by william20111** [william20111/go-thousandeyes#26]
## Story

As a developer I would like client support to create `voice-call` tests

## Detail

Should have consistent API like other test support & similar test coverage

* Support Creating `voice-call` tests
* Support Delete `voice-call` tests
* Support Update `voice-call` tests
* Support Get `voice-call` tests

**Comment by johntdyer** [comment]
https://github.com/william20111/go-thousandeyes/pull/22

**Comment by william20111** [comment]
This was fixed with @johntdyer PR in #22
