### ISSUE TITLE
Contributer access

### ISSUE THREAD

**Issue by johntdyer** [william20111/go-thousandeyes#72]
@william20111  

I know you're probably busy so I was wondering if you might entertain granting me access to merge PR's for these two repositories ?   Maybe that way I can help review and merge ?

Regards,

John

**Comment by johntdyer** [comment]
Thanks @william20111

**Comment by johntdyer** [comment]
@william20111  should I be able to merge PR's w/ the access ?

**Comment by william20111** [comment]
https://github.com/william20111/go-thousandeyes/pull/73

Sorry this should fix it.

**Comment by johntdyer** [comment]
@william20111  ok, so given that change should I be able to merge https://github.com/william20111/go-thousandeyes/pull/68 ?

**Comment by william20111** [comment]
if the branch is updated to latest master then yes you can review and merge as you are a code reviewer now

**Comment by johntdyer** [comment]
@william20111  so it still says I cant, even when I make sure my branch is updated to master for my PR ( #68 )

![image](https://user-images.githubusercontent.com/58234/111187226-340a3f80-858a-11eb-8a71-ecbf36ef6dca.png)

**Comment by johntdyer** [comment]
@william20111  so the only one I cant merge is apparently my own... I was able to merge Josh's

**Comment by william20111** [comment]
Ah yes. I'll review and merge.

**Comment by johntdyer** [comment]
so I am not versed w/ Github Actions... do I need to just create a tag to cut a new release and it will do it automagically ?
